spring:

  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:h2:file:./target/h2db/db/faasmanagerserver;DB_CLOSE_DELAY=-1
#    username: FaasManagerServer
#    password:

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123qwe!@#
#    url: jdbc:mysql://localhost:30813/faasT1?createDatabaseIfNotExist=true&useUnicode=true&character_set_server=utf8
    url: jdbc:mysql://localhost:30813/faasT2?useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
  #    url: jdbc:mysql://localhost:30813/faas?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
  h2:
    console:
      enabled: true


  liquibase:
    contexts: dev, faker
#    url: jdbc:h2:file:./target/h2db/db/faasmanagerserver;DB_CLOSE_DELAY=-1
    # 开启 liquibase
    enabled: true
    # 配置 changlog 文件路径
    change-log: classpath:/db/master.xml
server:
  port: 8080



